import './globals.css'

import type { Metadata } from 'next'
import { ReactNode } from 'react'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Prueba técnica ContactShip • Juan Agustín Lovera',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => (
  <html lang="es">
    <body className={`${inter.className} relative bg-indigo-50`}>
      <span className="fixed right-0 top-0 h-[31.25rem] w-[31.25rem] -translate-x-[80%] translate-y-[20%] rounded-full bg-blue-300 blur-[6rem] opacity-50"></span>
      {children}
    </body>
  </html>
)

export default RootLayout
